# Server base de donn√©es pgsql et web pour de la data vis

services:
  db:
    image: postgres:15
    container_name: los-shinigamis-db
    command: postgres -c datestyle='iso, dmy'
    environment:
      POSTGRES_USER: shinigami
      POSTGRES_PASSWORD: shinigami_password
      POSTGRES_DB: shinigami_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
    ports:
      - "5432:5432"

volumes:
  db_data: