# Server base de donn√©es pgsql et web pour de la data vis

services:
  db:
    image: postgres:18
    container_name: los-shinigamis-db
    command: postgres -c datestyle='iso, dmy'
    environment:
      POSTGRES_USER: shinigami
      POSTGRES_PASSWORD: shinigami_password
      POSTGRES_DB: shinigami_db
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
    ports:
      - "5432:5432"
    networks:
      - backend


  api:
    build:
      context: api
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend

  dashboard:
    build:
      context: dashboard
    volumes:
      - ./dashboard:/app
      - ./dashboard/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - frontend



networks:
  backend:
  frontend:
